"""
Language translations for ShopEase Copilot
Supports: English, Telugu, Hindi
"""

LANGUAGE_MAP = {
    "English": {
        "greeting": "Welcome to ShopEase Copilot!",
        "search_prompt": "Search products",
        "select_language": "Select Language",
        "add_to_cart": "Add to Cart",
        "cart_title": "Shopping Cart",
        "total": "Total",
        "empty_cart": "Your cart is empty.",
        "items": "Items",
        "price": "Price",
        "rating": "Rating",
        "reviews": "Reviews",
        "recommendation": "Recommended products",
        "added_to_cart": "Added to cart!",
        "could_not_understand": "Could not understand that.",
        "product_not_found": "I couldn't find that product.",
        "details_intro": "Here are the details:",
        "compare_intro": "Comparing products:",
        "added_to_cart_confirmation": "I added the product to your cart.",
        "show_top": "Show top products",
        "checkout_confirmation": "Order confirmed! Thank you for shopping.",
        "listening": "Listening...",
        "speaking": "Speaking...",
        "error_microphone": "Microphone not available.",
        "error_network": "Network error occurred.",
        "error_recognition": "Speech not recognized. Please try again.",
        "checkout": "Checkout",
        "clear_cart": "Clear Cart",
        "quantity": "Qty",
        "voice_input": "Voice Input",
        "type_or_speak": "Type a command or click the microphone icon",
        "language": "Language",
        "products_catalog": "Products Catalog",
        "brand": "Brand",
    },
    "Telugu": {
        "greeting": "షాప్ ఈజ్ కోపైలట్‌కు స్వాగతం!",
        "search_prompt": "ఉత్పత్తులను శోధించండి",
        "select_language": "భాష ఎంచుకోండి",
        "add_to_cart": "కార్ట్‌లో జోడించండి",
        "cart_title": "కార్ట్",
        "total": "మొత్తం",
        "empty_cart": "మీ కార్ట్ ఖాళీగా ఉంది.",
        "items": "అంశాలు",
        "price": "ధర",
        "rating": "రేటింగ్",
        "reviews": "విమర్శలు",
        "recommendation": "సిఫార్సు చేసిన ఉత్పత్తులు",
        "added_to_cart": "కార్ట్‌లో జోడించబడింది!",
        "could_not_understand": "శబ్దం అర్థం కాలేదు.",
        "product_not_found": "ఆ ఉత్పత్తిని కనుక్కోవలేకపోయాను.",
        "details_intro": "ఇవి వివరాలు:",
        "compare_intro": "ఉత్పత్తులతో పోల్చుతున్నాను:",
        "added_to_cart_confirmation": "ఉత్పత్తిని కార్ట్‌లో జోడించాను.",
        "show_top": "ఉన్నత ఉత్పత్తులను చూపించండి",
        "checkout_confirmation": "ఆర్డర్ నిర్ధారణ! కేనీయకు ధన్యవాదాలు.",
        "listening": "వింటున్నాను...",
        "speaking": "మాట్లాడుతున్నాను...",
        "error_microphone": "మైక్రోఫోన్ అందుబాటులో లేనిది.",
        "error_network": "నెట్‌వర్క్ లోపం సంభవించింది.",
        "error_recognition": "శబ్దం గుర్తించబడలేదు. మళ్లీ ప్రయత్నించండి.",
        "checkout": "చెక్‌అవుట్",
        "clear_cart": "కార్ట్ క్లియర్ చేయండి",
        "quantity": "పరిమాణం",
        "voice_input": "వాయిస్ ఇన్‌పుట్",
        "type_or_speak": "ఆదేశం టైప్ చేయండి లేదా మైక్రోఫోన్ చిహ్నం క్లిక్ చేయండి",
        "language": "భాష",
        "products_catalog": "ఉత్పత్తుల కేటలాగ్",
        "brand": "బ్రాండ్",
    },
    "Hindi": {
        "greeting": "ShopEase Copilot में आपका स्वागत है!",
        "search_prompt": "उत्पाद खोजें",
        "select_language": "भाषा चुनें",
        "add_to_cart": "कार्ट में डालें",
        "cart_title": "कार्ट",
        "total": "कुल",
        "empty_cart": "आपकी कार्ट खाली है।",
        "items": "आइटम",
        "price": "कीमत",
        "rating": "रेटिंग",
        "reviews": "समीक्षाएँ",
        "recommendation": "अनुशंसित उत्पाद",
        "added_to_cart": "कार्ट में जोड़ा गया!",
        "could_not_understand": "ध्वनि समझ में नहीं आई।",
        "product_not_found": "उस उत्पाद को नहीं ढूंढ पाया।",
        "details_intro": "यहाँ विवरण हैं:",
        "compare_intro": "उत्पादों की तुलना:",
        "added_to_cart_confirmation": "उत्पाद को कार्ट में जोड़ा गया।",
        "show_top": "शीर्ष उत्पाद दिखाएं",
        "checkout_confirmation": "आदेश की पुष्टि! खरीदारी के लिए धन्यवाद।",
        "listening": "सुन रहा हूँ...",
        "speaking": "बोल रहा हूँ...",
        "error_microphone": "माइक्रोफ़ोन उपलब्ध नहीं है।",
        "error_network": "नेटवर्क त्रुटि हुई।",
        "error_recognition": "ध्वनि पहचानी नहीं जा सकी। कृपया दोबारा प्रयास करें।",
        "checkout": "चेकआउट",
        "clear_cart": "कार्ट साफ़ करें",
        "quantity": "मात्रा",
        "voice_input": "वॉयस इनपुट",
        "type_or_speak": "कमांड टाइप करें या माइक्रोफ़ोन आइकन पर क्लिक करें",
        "language": "भाषा",
        "products_catalog": "उत्पाद कैटलॉग",
        "brand": "ब्रांड",
    },
}


def get_language_labels(language: str) -> dict[str, str]:
    """
    Get language labels for the specified language.
    
    Args:
        language: Language code (English, Telugu, Hindi)
    
    Returns:
        Dictionary of translated labels
    """
    return LANGUAGE_MAP.get(language, LANGUAGE_MAP["English"])
