from __future__ import annotations


LANGUAGE_MAP = {
    "English": {
        "greeting": "Welcome to ShopEase Copilot!",
        "search_prompt": "Search products",
        "select_language": "Language",
        "add_to_cart": "Add to Cart",
        "cart_title": "Cart",
        "total": "Total",
        "empty_cart": "Your cart is empty.",
        "items": "Items",
        "price": "Price",
        "rating": "Rating",
        "reviews": "Reviews",
        "recommendation": "Recommended products",
        "added_to_cart": "Added to cart.",
        "could_not_understand": "Could not understand that.",
        "product_not_found": "I couldn't find that product.",
        "details_intro": "Here are the details:",
        "compare_intro": "Comparing products:",
        "added_to_cart_confirmation": "I added the product to your cart.",
    },
    "Telugu": {
        "greeting": "షాప్ ఈజ్ కోపైలట్‌కు స్వాగతం!",
        "search_prompt": "ఉత్పత్తులను శోధించండి",
        "select_language": "భాష",
        "add_to_cart": "కార్ట్‌లో జోడించండి",
        "cart_title": "కార్ట్",
        "total": "మొత్తం",
        "empty_cart": "మీ కార్ట్ ఖాళీగా ఉంది.",
        "items": "అంశాలు",
        "price": "ధర",
        "rating": "రేటింగ్",
        "reviews": "విమర్శలు",
        "recommendation": "సిఫార్సు చేసిన ఉత్పత్తులు",
        "added_to_cart": "కార్ట్‌లో జోడించబడింది.",
        "could_not_understand": "శబ్దం అర్థం కాలేదు.",
        "product_not_found": "ఆ ఉత్పత్తిని కనుక్కోవలేకపోయాను.",
        "details_intro": "ఇవి వివరాలు:",
        "compare_intro": "ఉత్పత్తులతో పోల్చుతున్నాను:",
        "added_to_cart_confirmation": "రెండవ ఉత్పత్తిని కార్ట్‌లో జోడించాను.",
    },
    "Hindi": {
        "greeting": "ShopEase Copilot में आपका स्वागत है!",
        "search_prompt": "उत्पादन खोजें",
        "select_language": "भाषा",
        "add_to_cart": "कार्ट में डालें",
        "cart_title": "कार्ट",
        "total": "कुल",
        "empty_cart": "आपकी कार्ट खाली है।",
        "items": "आइटम",
        "price": "कीमत",
        "rating": "रेटिंग",
        "reviews": "समीक्षाएँ",
        "recommendation": "अनुशंसित उत्पाद",
        "added_to_cart": "कार्ट में जोड़ा गया।",
        "could_not_understand": "ध्वनि समझ में नहीं आई।",
        "product_not_found": "उस उत्पाद को नहीं ढूंढ पाया।",
        "details_intro": "यहाँ विवरण हैं:",
        "compare_intro": "उत्पादों की तुलना:",
        "added_to_cart_confirmation": "दूसरे उत्पाद को कार्ट में जोड़ा गया।",
    },
}


def get_language_labels(language: str) -> dict[str, str]:
    return LANGUAGE_MAP.get(language, LANGUAGE_MAP["English"])
